### PR TITLE
#52 - Visual improvements

### PR DESCRIPTION
**Pull request by isaacdurazo**

### CODE REVIEW

**Comment by tkellen** [comment]
@isaacdurazo can we "upstream" the padding fixes @cowboy pointed out to bocoup.com?

**Comment by isaacdurazo** [comment]
Ok, all set @tkellen, @cowboy. But apparently there are some conflicts :(

**Comment by cowboy** [comment]
General feedback:

* It seems odd that the left nav is higher vertically than the main page header
* Nested list vertical spacing is still not quite right (the spacing after a nested `ul` and the next `li` is too large)



* The left nav width sometimes overlaps the body content:



* Can we add sub-items to the left nav, at least one extra level like so (only show the `nav-1` elements on mobile)? If so, maybe the nav shouldn't be fixed position.

```html
<li class="nav-1"><a href="#overview">Overview</a></li>
<li class="nav-1"><a href="#dependencies">Dependencies</a></li>
<li class="nav-1"><a href="#initial-setup">Initial Setup</a></li>
<li class="nav-1"><a href="#ansible">Ansible</a></li>
<li class="nav-2"><a href="#ansible-configuration">Ansible Configuration</a></li>
<li class="nav-2"><a href="#ansible-inventory">Ansible Inventory</a></li>
<li class="nav-2"><a href="#ansible-playbooks">Ansible Playbooks</a></li>
<li class="nav-2"><a href="#ansible-roles">Ansible Roles</a></li>
<li class="nav-1"><a href="#vagrant">Vagrant</a></li>
<li class="nav-2"><a href="#configuring-vagrant">Configuring Vagrant</a></li>
<li class="nav-2"><a href="#using-vagrant">Using Vagrant</a></li>
<li class="nav-2"><a href="#using-ssh-with-vagrant">Using SSH with Vagrant</a></li>
<li class="nav-1"><a href="#deploying">Deploying</a></li>
<li class="nav-2"><a href="#command-line-flags">Command Line Flags</a></li>
<li class="nav-2"><a href="#playbook-helper-script">Playbook helper script</a></li>
```

FWIW, I generated that list by loading jQuery into the page and running this:

```js
console.log($('h2,h3').map(function() {
  var e = $(this);
  var t = 'nav-'+(this.nodeName.slice(1)-1);
  var h = e.find('a').attr('href');
  return '<li class="'+t+'"><a href="'+h+'">'+e.text()+'</a></li>'
}).get().join('\n'))
```

* For some reason, the look of the left nav doesn't seem to fit with the rest of the page. I think it's because of all the padding.

**Comment by cowboy** [comment]
@isaacdurazo, try these padding and margin values:

```css
.post-body ul, .post-body ol {
  padding: 0 0 0 2.4em;
  margin: 0.8em 0 0 0;
}
.post-body li {
  padding: 0 0 0.8em;
}
.post-body li li:last-child {
  padding-bottom: 0;
}
```

**Comment by isaacdurazo** [comment]
Alright, all the issues should be fixed now.

**Comment by tkellen** [comment]
This looks fantastic @isaacdurazo!

**Comment by tkellen** [comment]
@cowboy Any feedback here?

**Comment by cowboy** [comment]
Wow, looks great @isaacdurazo!

I've made a handful of changes on top of your work, but don't have any more time to work on this today. @tkellen would it be possible for you to rebase this to remove @isaacdurazo's "conflicts" merges, and then deploy?

Thanks so much!

**Comment by tkellen** [comment]
rebased out the conflict commits, landing and deploying now!

**Pull request merged**
