### PR TITLE
prefer yaml format

### PR DESCRIPTION
**Pull request by tkellen**
cc @brianloveswords 
(I have no bug report for ansible on this one, yet)

### CODE REVIEW

**Comment by brianloveswords** [comment]
:+1: , something changed in latest ansible that breaks this?

**Comment by tkellen** [comment]
I *think* so. I haven't made an isolated test case tho (yet)

**Comment by cowboy** [comment]
I can't see why this wouldn't work. It might be a regression.

http://goo.gl/ip2P3h

**Comment by tkellen** [comment]
no bug here, but I do want to land for consistency sake.

**Pull request merged**
