### PR TITLE
only npm install if you need to

### PR DESCRIPTION
**Pull request by tkellen**
this should make deploys a **lot** faster.

### CODE REVIEW

**Comment by leobalter** [comment]
It skips bug patches on npm packages. NPM is not that slow if you reuse the current node_modules folder but still check what does need an update.

**Comment by tkellen** [comment]
@leobalter I don't want bugfixes in production.

**Comment by leobalter** [comment]
the changes seem good, but I'm still conservative on the packages.

Maybe the copy folder task followed by a npm install may help achieving a good performance improvement without preventing the production server to follow the same package versions.

I'm conservative but I'm not silver on this. As I mentioned, the changes look good.

Using fixed npm package versions is a great strategy using the current changes. Solves all of my personal concerns.

**Comment by cowboy** [comment]
1. Is it possible that any npm module might have a build process that requires an absolute path? If so, this could be problematic.
2. Why not use something like one of these, instead?
  * https://www.npmjs.com/package/npm-cache
  * https://github.com/mixu/npm_lazy

Also, see:

* http://soledadpenades.com/2015/05/31/npmoffline-installing-npm-packages-from-the-cache/
* https://github.com/npm/npm/issues/2568
* https://github.com/npm/npm/issues/8581

**Comment by tkellen** [comment]
1. I don't think so, but I'm not sure!
2. Would you be willing to explore a solution that uses your suggestion so we can compare the complexity of both and make a determination on which one we want to use?

**Comment by tkellen** [comment]
Hey @cowboy, if you're not interested in exploring option 2 yourself, I'm going to land this. I think it is a nice minimal solution to speeding up deploys that is easy to reason about. The only change I think I'd like to make before doing so is to ensure that when `force` is true, it doesn't re-use the existing `node_modules`.

**Comment by cowboy** [comment]
I don't have the time to do it before January. Do what you gotta do!

**Comment by tkellen** [comment]
No rush here--I'll land this and open an issue referencing your comment for further exploration.

**Pull request merged**
