### PR TITLE
Add some kind of service

### PR DESCRIPTION
**Pull request by cowboy**
I added a node-based socket.io server and some client code to show a "Viewing" counter in the top right as well as a little colored dot in the right side of the content area that moves as other current visitors scroll.

Try it out by visiting https://deployment-workflow-staging.bocoup.com/ in multiple windows simultaneously, and scrolling.

The thing is, while this works, it's not particularly obvious or interesting. But I think it could be the basis of something cool... I just need some ideas. Help?

Also, @tkellen can you review the related ansible / upstart / nginx changes?

### CODE REVIEW

**Comment by tkellen** [comment]
Maybe show the IP address next to the dot?

**Comment by tkellen** [comment]
Ansible portion looks good to me!

**Comment by jmeas** [comment]
This is definitely neat, but do we think it fits in with the 99% use case of modern web apps? Sockets are definitely cool, but I think their use case is small compared to good old HTTP.

I guess my concern is that the inclusion of sockets in the example might have the opposite effect of what we want, and actually potentially turn people off of the project.

Maybe I'm just being paranoid, tho'. It's super cool, either way!

**Comment by tkellen** [comment]
The primary driver behind adding a node service was to address #26. I think this does that and I'm not concerned about people being turned off by it.

**Comment by cowboy** [comment]
I'm in favor of closing this issue, I'm not satisfied that it's a good example.

**Pull request closed without merging**
