### PR TITLE
Update Node to use Node 4.2.x with LTS

### PR DESCRIPTION
**Pull request by leobalter**
Also documents a reference to Node 5

### CODE REVIEW

**Comment by leobalter** [comment]
It works perfectly on bocoup/new-people

**Comment by tkellen** [comment]
bless your heart @leobalter.

**Comment by tkellen** [comment]
testing to confirm this works for this project now.

**Comment by cowboy** [comment]
Nice.

**Comment by tkellen** [comment]
:+1: from me.

**Comment by cowboy** [comment]
If it works, awesome!

**Pull request merged**
