### PR TITLE
remove bower

### PR DESCRIPTION
**Pull request by tkellen**
This dependency is not needed for this project. Additionally, there are some minor conflicts with the stylesheet @isaacdurazo is working on.

/cc @cowboy

### CODE REVIEW

**Comment by isaacdurazo** [comment]
+1 @tkellen I don't think we should have this

**Comment by tkellen** [comment]
This is deployed @ http://deployment-workflow.bocoup.com for easy review.

**Comment by cowboy** [comment]
Please don't remove this code until the things that it actually does have been replaced, namely the clickable link icons that appear on hover of headers.

There may be other things, but I'm not sure offhand!

**Comment by cowboy** [comment]
Please deploy to a staging server for review!

**Comment by tkellen** [comment]
@isaacdurazo can you push an additional commit to the PR for this branch to restore the functionality @cowboy is referring to?

**Comment by isaacdurazo** [comment]
Sure thing, @tkellen

**Comment by isaacdurazo** [comment]
hey @tkellen, @cowboy I never saw the link/anchor functionality when I had the site running locally. Is that something like the blue links, that only is viewable in production?

**Comment by isaacdurazo** [comment]
Maybe we should just revert this commit

**Comment by cowboy** [comment]
@isaacdurazo the css lets you hover over headers and click the link icon that appears to the let for a bookmarkable anchor link.

**Comment by tkellen** [comment]
@isaacdurazo I just deployed the "original" version of the site so you can see it.

@cowboy I'm game to use a staging server once we've announced this publicly! Until then, I was just flying fast and loose in the hopes of keeping people unblocked.

**Comment by isaacdurazo** [comment]
Yah I know what it is @cowboy, but I never saw that when the site runs locally, just like the blue color in links. It's like Github's markdown CSS only works in production

**Comment by cowboy** [comment]
Before:


On Hover:


(the link icon is clickable)

**Comment by tkellen** [comment]
@isaacdurazo I'm guessing that's because you didn't run bower install locally for the project so the CSS wasn't present.

**Comment by isaacdurazo** [comment]
Ok just to confirm that I needed to run `bower install`, I can see it locally now

**Comment by isaacdurazo** [comment]
All set, @tkellen

**Comment by tkellen** [comment]
ready for your review @cowboy

**Comment by cowboy** [comment]
LGTM!

**Pull request merged**
